In [139]:
import numpy as np
import pandas as pd

In [140]:
df = pd.DataFrame([[8,8,4],[5,12,7],[7,9,5],[9,10,6]], columns=['cgpa', 'rs', 'lpa'])

In [141]:
df.head()

cgpa  rs  lpa
0     8   8    4
1     5  12    7
2     7   9    5
3     9  10    6

In [142]:
def initialize_parameters(layers_dims):
    """
    Arguments:
    layers_dims -- python list containing the dimensions of each layer in our network

    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layers_dims[l], layers_dims[l-1])
                    bl -- bias vector of shape (layers_dims[l], 1)
    """
    np.random.seed(3) # to keep consistent results
    parameters = {}
    L = len(layers_dims)            # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layers_dims[l], layers_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))

        assert(parameters['W' + str(l)].shape == (layers_dims[l], layers_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layers_dims[l], 1))

    return parameters

In [143]:
initialize_parameters([2,2,1])

{'W1': array([[ 0.01788628,  0.0043651 ],
        [ 0.00096497, -0.01863493]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[-0.00277388, -0.00354759]]),
 'b2': array([[0.]])}

In [144]:
# Forward Prop
def linear_forward(A_prev, W, b):
    """
    Implements the linear part of a layer's forward propagation.

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples in the current layer)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter
    cache -- a python dictionary containing "A_prev", "W" and "b" ; stored for computing the backward pass efficiently
    """
    Z = np.dot(W.T, A_prev) + b

    return Z

def L_layer_forward(X, parameters):
  
  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)
  
    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)
          
  return A,A_prev

In [145]:
X = df[['cgpa', 'rs']].values[0]

In [146]:
X

array([8, 8])

In [147]:
df[['cgpa', 'rs','lpa']]

cgpa  rs  lpa
0     8   8    4
1     5  12    7
2     7   9    5
3     9  10    6

In [148]:
X = df[['cgpa', 'rs']].values[0].reshape(2,1)

In [149]:
X

array([[8],
       [8]])

In [150]:
y = df[['lpa']].values[0].reshape(1,1)
y

array([[4]])

In [151]:
parameters = initialize_parameters([2, 2, 1])
parameters

{'W1': array([[ 0.01788628,  0.0043651 ],
        [ 0.00096497, -0.01863493]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[-0.00277388, -0.00354759]]),
 'b2': array([[0.]])}

In [152]:
L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[ 0.01788628  0.0043651 ]
 [ 0.00096497 -0.01863493]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[ 0.15081008]
 [-0.11415863]]
****************************************
A1:  [[ 0.15081008]
 [-0.11415863]]
W2:  [[-0.00277388 -0.00354759]]
b2:  [[0.]]
----------------------------------------


ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)